defaults:
  - _self_
  - model:  xxz
  - ansatz: rbm
  - task: analysis_is

device: "5"
is_mode : null
solver_fn :
  _target_: netket.optimizer.solver.cholesky
  # _target_ : scipy.sparse.linalg.cg
lr : 0.0022
diag_shift : schedule
n_iter : 6000
sample_size : 9
chunk_size_jac: 1024
chunk_size_vmap : 100
save_every : 10
run_index : 0
base_path : /scratch/.amisery/grad_sample_fullsum/