defaults:
  - _self_
  - model:  xxz
  - ansatz: rbm
  - task: vmc_gs
  - solver_fn: cholesky
  - sampler: exact
  - is_distrib: overdispersed

auto_is: true
lr : 0.0022
diag_shift : 1e-4
callback_list: 
  - _target_ : grad_sample.utils.save_exact_err

n_iter: 2000
sample_size : 11
chunk_size_jac: 1024