defaults:
  - _self_
  - model: nitrogen
  - ansatz: nnbf
  - task: vmc_gs
  - solver_fn: cholesky
  - sampler: exact
  - is_distrib: overdispersed

ansatz:
  hidden_units: 16

n_iter : 500
lr:
  _target_: optax.linear_schedule
  init_value: 0.1
  transition_steps: 250
  end_value: 0.01

diag_shift: 1e-4

callback_list: 
  - _target_ : grad_sample.utils.save_exact_err
    save_every: 10

chunk_size_jac: 1024
chunk_size_vstate: 8192

sample_size : 10
momentum : 0.9
auto_is: false
collect_gradient_statistics: false
fullsum_eval: true
