defaults:
  - _self_
  - model: lithium_oxide
  - ansatz: nnbf
  - task: vmc_ng
  - solver_fn: cholesky
  - sampler: fermionhop
  - is_distrib: overdispersed

n_iter : 5000
lr:
  _target_: optax.linear_schedule
  init_value: 0.1
  transition_steps: 1000
  end_value: 0.01
                           
diag_shift:
  _target_: optax.linear_schedule
  init_value: 5e-3
  end_value: 1e-5,
  transition_steps: 500

callbacks:
  - callbacks/save_err_approx
  - callbacks/save_sampler_state

chunk_size_jac: 1024
chunk_size_vstate: 8192
chunk_size_vmap : 100

sample_size : 13
momentum : 0.9
auto_is: false
collect_gradient_statistics: false
