defaults:
  - _self_
  - model: j1j2
  - ansatz: vit
  - task: fullsum_gs
  - solver_fn: cholesky

model:
  J: [1.0, 0.5]
  L: 4

n_iter : 1000
lr:
  _target_: optax.linear_schedule
  init_value: 0.01
  transition_steps: 200
  end_value: 0.005
                         
diag_shift:
  _target_: optax.linear_schedule
  init_value: 0.01
  transition_steps: 300
  end_value: 1e-4

callback_list: 
  - _target_ : grad_sample.utils.compute_snr_callback
    save_every: 10
  - _target_ : grad_sample.utils.save_exact_err
    save_every: 10


