defaults:
  - _self_
  - model: nitrogen
  - ansatz: nnbf
  - task: fullsum_gs
  - solver_fn: cholesky

ansatz:
  hidden_units: 16

n_iter : 500
lr:
  _target_: optax.linear_schedule
  init_value: 0.1
  transition_steps: 500
  end_value: 0.01
                         
diag_shift: 2e-4

callback_list: 
  - _target_ : grad_sample.utils.compute_snr_callback
    save_every: 10
  - _target_ : grad_sample.utils.save_exact_err
    save_every: 10