defaults:
  - _self_
  - model: j1j2
  - ansatz: vit
  - task: vmc_gs
  - solver_fn: cholesky
  - sampler: exact
  - is_distrib: overdispersed


n_iter : 1000
lr:
  _target_: optax.linear_schedule
  init_value: 0.005
  transition_steps: 100
  end_value: 0.002
                         
diag_shift:
  _target_: optax.linear_schedule
  init_value: 0.01
  transition_steps: 200
  end_value: 0.0001
callback_list: 
  - _target_ : grad_sample.utils.save_exact_err
    save_every: 10


sample_size : 13
momentum : 0.9
auto_is: false
collect_gradient_statistics: false
